#!/usr/bin/env node

/**
 * Build script to create browser-compatible bundle
 * Combines all TypeScript-compiled modules into a single browser file
 */

const fs = require('fs');
const path = require('path');

// Read all compiled modules
const distDir = path.join(__dirname, 'dist');

// Order matters - dependencies first
const modules = [
  'types/index.js',
  'utils/color.js',
  'modules/adjustment.js',
  'modules/compiler.js',
  'modules/expansion.js',
  'modules/renderer.js',
  'contextfree.js'
];

let bundleCode = `/**
 * ContextFree.js - Browser Bundle
 * Generated from TypeScript source
 * DO NOT EDIT THIS FILE DIRECTLY
 */

(function() {
  'use strict';
  
  // Simple module system for browser
  var modules = {};
  var exports = {};
  
  function require(name) {
    if (modules[name]) {
      return modules[name];
    }
    throw new Error('Module not found: ' + name);
  }
  
`;

// Read each module and wrap it
modules.forEach(modulePath => {
  const fullPath = path.join(distDir, modulePath);
  const moduleCode = fs.readFileSync(fullPath, 'utf8');
  
  // Remove source map comments
  const cleanCode = moduleCode.replace(/\/\/# sourceMappingURL=.*/g, '');
  
  // Extract the module name (without .js)
  const moduleName = './' + modulePath.replace(/\.js$/, '');
  
  bundleCode += `  // Module: ${moduleName}\n`;
  bundleCode += `  modules['${moduleName}'] = (function() {\n`;
  bundleCode += `    var exports = {};\n`;
  bundleCode += `    var module = { exports: exports };\n`;
  
  // Add the module code with indentation
  const lines = cleanCode.split('\n');
  lines.forEach(line => {
    // Skip "use strict" as we already have it
    if (line.trim() === '"use strict";' || line.trim() === "'use strict';") {
      return;
    }
    bundleCode += `    ${line}\n`;
  });
  
  bundleCode += `    return module.exports.ContextFree || module.exports;\n`;
  bundleCode += `  })();\n\n`;
});

bundleCode += `
  // Export the main ContextFree class to global scope
  var ContextFreeModule = modules['./contextfree'];
  if (typeof window !== 'undefined') {
    window.ContextFree = ContextFreeModule.ContextFree || ContextFreeModule;
  }
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = ContextFreeModule.ContextFree || ContextFreeModule;
  }
  
})();
`;

// Write the bundle
const outputPath = path.join(__dirname, 'contextfree.js');
fs.writeFileSync(outputPath, bundleCode);
console.log('Successfully created browser bundle: contextfree.js');
