/**
 * ContextFree.js - Browser Bundle
 * Generated from TypeScript source
 * DO NOT EDIT THIS FILE DIRECTLY
 */

(function() {
  'use strict';
  
  // Simple module system for browser
  var modules = {};
  var exports = {};
  
  function require(name) {
    if (modules[name]) {
      return modules[name];
    }
    throw new Error('Module not found: ' + name);
  }
  
  // Module: ./types/index
  modules['./types/index'] = (function() {
    var exports = {};
    var module = { exports: exports };
    /**
     * Type definitions for ContextFree.js
     */
    Object.defineProperty(exports, "__esModule", { value: true });
    
    return module.exports.ContextFree || module.exports;
  })();

  // Module: ./utils/color
  modules['./utils/color'] = (function() {
    var exports = {};
    var module = { exports: exports };
    /**
     * Color utility functions
     */
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.hsv2rgb = hsv2rgb;
    /**
     * Convert HSV color to RGB
     * @param h - Hue (0-360)
     * @param s - Saturation (0-1)
     * @param v - Value/Brightness (0-1)
     * @param a - Alpha (0-1)
     * @returns RGB color with alpha [r, g, b, a]
     */
    function hsv2rgb(h, s, v, a) {
        let r, g, b;
        if (s === 0) {
            r = g = b = Math.round(v * 0xff);
        }
        else {
            v *= 0xff;
            h = ((h %= 360) < 0 ? h + 360 : h) / 60;
            const hi = h | 0;
            switch (hi) {
                case 0:
                    r = Math.round(v);
                    g = Math.round(v * (1 - (1 - h + hi) * s));
                    b = Math.round(v * (1 - s));
                    break;
                case 1:
                    r = Math.round(v * (1 - s * h + s * hi));
                    g = Math.round(v);
                    b = Math.round(v * (1 - s));
                    break;
                case 2:
                    r = Math.round(v * (1 - s));
                    g = Math.round(v);
                    b = Math.round(v * (1 - (1 - h + hi) * s));
                    break;
                case 3:
                    r = Math.round(v * (1 - s));
                    g = Math.round(v * (1 - s * h + s * hi));
                    b = Math.round(v);
                    break;
                case 4:
                    r = Math.round(v * (1 - (1 - h + hi) * s));
                    g = Math.round(v * (1 - s));
                    b = Math.round(v);
                    break;
                case 5:
                    r = Math.round(v);
                    g = Math.round(v * (1 - s));
                    b = Math.round(v * (1 - s * h + s * hi));
                    break;
                default:
                    r = g = b = 0;
            }
        }
        return [r, g, b, a];
    }
    
    return module.exports.ContextFree || module.exports;
  })();

  // Module: ./modules/adjustment
  modules['./modules/adjustment'] = (function() {
    var exports = {};
    var module = { exports: exports };
    /**
     * Adjustment module - handles transformations and color adjustments
     */
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.adjustTransform = adjustTransform;
    exports.adjustColor = adjustColor;
    /**
     * Apply a transformation adjustment to an existing transform
     * @param transform - Current transformation matrix
     * @param adjustment - Adjustment transformation to apply
     * @returns New transformation matrix
     */
    function adjustTransform(transform, adjustment) {
        return [
            transform[0] * adjustment[0] + transform[2] * adjustment[1],
            transform[1] * adjustment[0] + transform[3] * adjustment[1],
            transform[0] * adjustment[2] + transform[2] * adjustment[3],
            transform[1] * adjustment[2] + transform[3] * adjustment[3],
            transform[0] * adjustment[4] + transform[2] * adjustment[5] + transform[4],
            transform[1] * adjustment[4] + transform[3] * adjustment[5] + transform[5]
        ];
    }
    /**
     * Adjust a color based on adjustment values
     * @param color - Current color [h, s, v, a]
     * @param adjustment - Adjustment values
     * @param target - Target color for relative adjustments
     * @returns New adjusted color
     */
    function adjustColor(color, adjustment, target) {
        const result = color.slice();
        let a, t;
        // Adjust hue
        if ((a = adjustment[0])) {
            if (adjustment[4] & 1) {
                t = target[0];
                if (a > 0) {
                    if (t < result[0])
                        t += 360;
                    result[0] += (t - result[0]) * a;
                }
                else {
                    if (t > result[0])
                        t -= 360;
                    result[0] += (result[0] - t) * a;
                }
            }
            else {
                result[0] += adjustment[0];
            }
            result[0] %= 360;
            if (result[0] < 0)
                result[0] += 360;
        }
        // Adjust saturation, brightness, and alpha
        for (let i = 1; i < 4; i++) {
            if ((a = adjustment[i])) {
                if (adjustment[4] & (1 << i)) {
                    if (a > 0) {
                        result[i] += (target[i] - result[i]) * a;
                    }
                    else {
                        result[i] += (result[i] - (result[i] < target[i] ? 0 : 1)) * a;
                    }
                }
                else {
                    if (a > 0) {
                        result[i] += (1 - result[i]) * a;
                    }
                    else {
                        result[i] += result[i] * a;
                    }
                }
            }
        }
        return result;
    }
    
    return module.exports.ContextFree || module.exports;
  })();

  // Module: ./modules/compiler
  modules['./modules/compiler'] = (function() {
    var exports = {};
    var module = { exports: exports };
    /**
     * Compiler module - compiles CFDG statements into executable functions
     */
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.compileAdjustment = compileAdjustment;
    exports.compileReplacement = compileReplacement;
    exports.compileReplacements = compileReplacements;
    exports.compilePath = compilePath;
    const adjustment_1 = require("./modules/adjustment");
    /**
     * Compile adjustment statements into executable form
     * @param adjustments - Array of adjustments from parser
     * @returns Compiled adjustment object
     */
    function compileAdjustment(adjustments) {
        const geomAdjustments = ['XSHIFT', 'YSHIFT', 'ZSHIFT', 'ROTATE', 'SIZE', 'SKEW', 'FLIP'];
        const colorAdjustments = ['HUE', 'SATURATION', 'BRIGHTNESS', 'ALPHA'];
        let transform = [1, 0, 0, 1, 0, 0];
        const color = [];
        const targetColor = [];
        let z = 0;
        let zScale = 1;
        const ordered = adjustments[2];
        const adjustmentList = adjustments[1].slice();
        adjustmentList.forEach((adjustment) => {
            adjustmentList[adjustment[0]] = adjustment;
        });
        const toProcess = ordered
            ? adjustmentList
            : geomAdjustments.reduce((result, type) => {
                if (type in adjustmentList)
                    result.push(adjustmentList[type]);
                return result;
            }, []);
        toProcess.forEach((adjustment) => {
            let x, y, c, s;
            switch (adjustment[0]) {
                case 'XSHIFT':
                    x = adjustment[1];
                    transform = (0, adjustment_1.adjustTransform)(transform, [1, 0, 0, 1, x, 0]);
                    break;
                case 'YSHIFT':
                    y = adjustment[1];
                    transform = (0, adjustment_1.adjustTransform)(transform, [1, 0, 0, 1, 0, y]);
                    break;
                case 'ZSHIFT':
                    z += adjustment[1];
                    break;
                case 'ROTATE':
                    c = Math.cos(Math.PI * adjustment[1] / 180);
                    s = Math.sin(Math.PI * adjustment[1] / 180);
                    transform = (0, adjustment_1.adjustTransform)(transform, [c, s, -s, c, 0, 0]);
                    break;
                case 'SIZE':
                    x = adjustment[1];
                    y = adjustment[2];
                    transform = (0, adjustment_1.adjustTransform)(transform, [x, 0, 0, y, 0, 0]);
                    zScale *= adjustment[3];
                    break;
                case 'SKEW':
                    x = Math.tan(Math.PI * adjustment[1] / 180);
                    y = Math.tan(Math.PI * adjustment[2] / 180);
                    transform = (0, adjustment_1.adjustTransform)(transform, [1, y, x, 1, 0, 0]);
                    break;
                case 'FLIP':
                    c = Math.cos(Math.PI * adjustment[1] / 90);
                    s = Math.sin(Math.PI * adjustment[1] / 90);
                    transform = (0, adjustment_1.adjustTransform)(transform, [c, s, s, -c, 0, 0]);
                    break;
            }
        });
        colorAdjustments.forEach((type, i) => {
            let adjustment;
            if ((adjustment = adjustmentList[type])) {
                color[i] = adjustment[1];
                if (adjustment[2])
                    color[4] |= (1 << i);
            }
            if ((adjustment = adjustmentList['TARGET' + type])) {
                targetColor[i] = adjustment[1];
            }
        });
        return {
            transform,
            color,
            targetColor,
            z,
            zScale
        };
    }
    /**
     * Compile a single replacement into an executable function
     * @param replacement - Replacement statement from parser
     * @returns Compiled replacement function
     */
    function compileReplacement(replacement) {
        const adjustment = compileAdjustment.call(this, replacement[2]);
        if (replacement[0] === 'REPLACEMENT') {
            const rules = this.rules[replacement[1]];
            if (rules == null) {
                throw new Error(`rule '${replacement[1]}' is not defined`);
            }
            return function (transform, color, targetColor, z, zScale) {
                const area = Math.abs(transform[0] * transform[3] - transform[1] * transform[2]);
                if (area * this.scale * this.scale < 0.3)
                    return;
                transform = (0, adjustment_1.adjustTransform)(transform, adjustment.transform);
                if (adjustment.color.length) {
                    color = (0, adjustment_1.adjustColor)(color, adjustment.color, targetColor);
                }
                if (adjustment.targetColor.length) {
                    targetColor = (0, adjustment_1.adjustColor)(targetColor, adjustment.targetColor);
                }
                z += adjustment.z * zScale;
                zScale *= adjustment.zScale;
                let rule;
                if (rules.length > 1) {
                    let p = 0;
                    const r = Math.random();
                    for (let i = 0, len = rules.length; i < len; i++) {
                        p += rules[i].probability;
                        if (r < p) {
                            rule = rules[i];
                            break;
                        }
                    }
                    rule = rule || rules[0];
                }
                else {
                    rule = rules[0];
                }
                const modification = [transform, color, targetColor, z, zScale];
                Array.prototype.push.apply(this.stack, rule.replacements.map((replacement) => {
                    return function () {
                        replacement.call(this, ...modification);
                    };
                }));
            };
        }
        if (replacement[0] === 'REPLACEMENT_LOOP') {
            const replacements = compileReplacements.call(this, replacement[3]);
            return function (transform, color, targetColor, z, zScale) {
                const area = Math.abs(transform[0] * transform[3] - transform[1] * transform[2]);
                if (area * this.scale * this.scale < 0.3)
                    return;
                let n = Number(replacement[1]);
                while (n-- > 0) {
                    const modification = [transform, color, targetColor, z, zScale];
                    Array.prototype.push.apply(this.stack, replacements.map((replacement) => {
                        return function () {
                            replacement.call(this, ...modification);
                        };
                    }));
                    if (!n)
                        return;
                    transform = (0, adjustment_1.adjustTransform)(transform, adjustment.transform);
                    if (adjustment.color.length) {
                        color = (0, adjustment_1.adjustColor)(color, adjustment.color, targetColor);
                    }
                    if (adjustment.targetColor.length) {
                        targetColor = (0, adjustment_1.adjustColor)(targetColor, adjustment.targetColor);
                    }
                    z += adjustment.z * zScale;
                    zScale *= adjustment.zScale;
                }
            };
        }
        throw new Error(`Unknown replacement type: ${replacement[0]}`);
    }
    /**
     * Compile multiple replacements
     * @param replacements - Array of replacements from parser
     * @returns Array of compiled replacement functions
     */
    function compileReplacements(replacements) {
        return replacements
            .map((replacement, i) => {
            return {
                replacement,
                index: replacement[1] in this.primitives ? replacements.length - i : -1
            };
        })
            .sort((a, b) => a.index - b.index)
            .map((o) => compileReplacement.call(this, o.replacement));
    }
    /**
     * Compile a path definition (not yet implemented)
     * @param _path - Path statement from parser
     * @returns Compiled path function
     */
    function compilePath(_path) {
        // Path compilation not yet implemented
        return undefined;
    }
    
    return module.exports.ContextFree || module.exports;
  })();

  // Module: ./modules/expansion
  modules['./modules/expansion'] = (function() {
    var exports = {};
    var module = { exports: exports };
    /**
     * Expansion module - handles shape expansion and generation
     */
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.expandShape = expandShape;
    exports.loop = loop;
    /**
     * Initialize and expand shapes from the start shape
     */
    function expandShape(drawCallback) {
        const modification = [
            [1, 0, 0, 1, 0, 0],
            [0, 0, 0, 1],
            [0, 0, 0, 1],
            0,
            1
        ];
        this.stack = [
            function () {
                this.startshape.apply(this, modification);
            }
        ];
        this.shapes = [];
        loop(function () {
            this.stack.pop().call(this);
            return this.stack.length;
        }.bind(this), drawCallback, this);
    }
    /**
     * Loop function that processes shapes in batches with timing control
     * @param loopFn - Function to call repeatedly
     * @param callback - Callback when loop completes
     * @param context - Context to bind to loop function
     */
    function loop(loopFn, callback, context) {
        const intervalContext = {
            intervalID: null,
            count: 0
        };
        if (intervalContext.intervalID) {
            window.clearInterval(intervalContext.intervalID);
        }
        const intervalID = window.setInterval(() => {
            let shouldContinue = true;
            const start = Date.now();
            do {
                let n = 1000;
                while (--n && shouldContinue) {
                    shouldContinue = loopFn.call(context);
                }
            } while (Date.now() - start < 30 && shouldContinue);
            if (!shouldContinue) {
                window.clearInterval(intervalID);
                callback.call(context);
            }
            else if (intervalContext.count++ > 3000) {
                window.clearInterval(intervalID);
                throw new Error('too much shapes');
            }
        }, 30);
        intervalContext.intervalID = intervalID;
    }
    
    return module.exports.ContextFree || module.exports;
  })();

  // Module: ./modules/renderer
  modules['./modules/renderer'] = (function() {
    var exports = {};
    var module = { exports: exports };
    /**
     * Renderer module - handles drawing shapes to canvas
     */
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.drawShape = drawShape;
    exports.stop = stop;
    exports.initializeCanvas = initializeCanvas;
    const color_1 = require("./utils/color");
    const expansion_1 = require("./modules/expansion");
    /**
     * Draw all generated shapes to the canvas
     */
    function drawShape() {
        // Sort shapes by z-order and area
        this.shapes.sort((a, b) => b.z - a.z || a.area - b.area);
        // Remove shapes that are too small to see
        let i = 0;
        const len = this.shapes.length;
        while (i < len && this.shapes[i].area * this.scale * this.scale < 0.3)
            i++;
        this.shapes.splice(0, i);
        if (!this.shapes.length) {
            stop.call(this);
            return;
        }
        // Recalculate bounds if not clipping
        if (!this.clip) {
            this.left = this.right = 0;
            this.top = this.bottom = 0;
            this.shapes.forEach((shape) => {
                if (this.left > shape.left)
                    this.left = shape.left;
                if (this.right < shape.right)
                    this.right = shape.right;
                if (this.top > shape.top)
                    this.top = shape.top;
                if (this.bottom < shape.bottom)
                    this.bottom = shape.bottom;
            });
            this.x = -(this.left + this.right) / 2;
            this.y = -(this.top + this.bottom) / 2;
        }
        // Set up the canvas transform
        this.context.translate(this.canvas.width / 2, this.canvas.height / 2);
        this.context.scale(this.scale, -this.scale);
        this.context.translate(this.x, this.y);
        // Draw shapes
        (0, expansion_1.loop)(function () {
            const shape = this.shapes.pop();
            this.context.save();
            this.context.transform(...shape.transform);
            this.context.fillStyle = 'rgba(' + (0, color_1.hsv2rgb)(...shape.color).join(',') + ')';
            this.context.scale(1.025, 1.025);
            shape.render.call(this);
            this.context.restore();
            return this.shapes.length;
        }.bind(this), () => stop.call(this), this);
    }
    /**
     * Stop the rendering process
     */
    function stop() {
        if (this.intervalID) {
            window.clearInterval(this.intervalID);
            this.intervalID = null;
        }
        if (this.callback) {
            this.callback.call(null);
            this.callback = null;
        }
    }
    /**
     * Initialize rendering - clear canvas and set background
     */
    function initializeCanvas(background) {
        this.context.setTransform(1, 0, 0, 1, 0, 0);
        this.context.clearRect(0, 0, this.canvas.width, this.canvas.height);
        if (background) {
            this.context.fillStyle = 'rgba(' + (0, color_1.hsv2rgb)(...background).join(',') + ')';
            this.context.fillRect(0, 0, this.canvas.width, this.canvas.height);
        }
    }
    
    return module.exports.ContextFree || module.exports;
  })();

  // Module: ./contextfree
  modules['./contextfree'] = (function() {
    var exports = {};
    var module = { exports: exports };
    /**
     * ContextFree.js - TypeScript implementation
     * Main class that orchestrates parsing, compilation, expansion, and rendering
     */
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.ContextFree = void 0;
    const adjustment_1 = require("./modules/adjustment");
    const compiler_1 = require("./modules/compiler");
    const expansion_1 = require("./modules/expansion");
    const renderer_1 = require("./modules/renderer");
    /**
     * Main ContextFree class
     */
    class ContextFree {
        /**
         * Create a new ContextFree instance
         * @param source - CFDG source code
         * @param canvas - HTML canvas element to render to
         */
        constructor(source, canvas) {
            // Display properties
            this.x = 0;
            this.y = 0;
            this.left = 0;
            this.right = 0;
            this.top = 0;
            this.bottom = 0;
            this.width = 1;
            this.height = 1;
            this.clip = false;
            // Rules and primitives
            this.rules = {};
            this.primitives = {};
            // Start shape
            this.startshape = null;
            // Expansion and rendering state
            this.stack = [];
            this.shapes = [];
            // Timing and control
            this.intervalID = null;
            this.callback = null;
            this.canvas = canvas;
            this.context = canvas.getContext('2d');
            this.scale = Math.min(canvas.width, canvas.height);
            // Initialize primitives
            this.initializePrimitives();
            // Parse and process the source
            this.parseSource(source);
            // Compile rules
            this.compileRules();
            // Calculate scale if clipping is enabled
            if (this.clip) {
                this.scale = Math.min(canvas.width / this.width, canvas.height / this.height);
            }
            // Validate start shape
            if (!this.startshape) {
                throw new Error('startshape is not defined');
            }
        }
        /**
         * Initialize built-in primitive shapes
         */
        initializePrimitives() {
            this.primitives = {
                SQUARE: function () {
                    this.context.fillRect(-0.5, -0.5, 1, 1);
                },
                CIRCLE: function () {
                    this.context.beginPath();
                    this.context.arc(0, 0, 0.5, 0, Math.PI * 2, false);
                    this.context.fill();
                },
                TRIANGLE: function () {
                    this.context.beginPath();
                    this.context.moveTo(0, 0.57735);
                    this.context.lineTo(-0.5, -0.28828);
                    this.context.lineTo(0.5, -0.28828);
                    this.context.closePath();
                    this.context.fill();
                }
            };
        }
        /**
         * Parse CFDG source code
         */
        parseSource(source) {
            CFDG.yy.rand_static = Math.random();
            const statements = CFDG.parse(source);
            let startshapeName = null;
            statements.forEach((statement) => {
                switch (statement[0]) {
                    case 'STARTSHAPE':
                        // Store the startshape name for later compilation (after all rules are registered)
                        startshapeName = statement[1];
                        break;
                    case 'BACKGROUND':
                        const adjustment = compiler_1.compileAdjustment.call(this, statement[1]);
                        this.background = (0, adjustment_1.adjustColor)([0, 0, 1, 1], adjustment.color);
                        break;
                    case 'SIZE':
                        this.clip = true;
                        statement[1][1].forEach((adj) => {
                            switch (adj[0]) {
                                case 'XSHIFT':
                                    this.x = adj[1];
                                    break;
                                case 'YSHIFT':
                                    this.y = adj[1];
                                    break;
                                case 'SIZE':
                                    this.width = adj[1];
                                    this.height = adj[2];
                                    break;
                            }
                        });
                        break;
                    case 'RULE':
                        const rule = {
                            weight: statement[2],
                            replacements: statement[3]
                        };
                        if (this.rules[statement[1]] != null) {
                            this.rules[statement[1]].push(rule);
                        }
                        else {
                            this.rules[statement[1]] = [rule];
                        }
                        break;
                    case 'PATH':
                        this.primitives[statement[1]] = compiler_1.compilePath.call(this, statement[2]);
                        break;
                }
            });
            // Compile the startshape after all rules have been registered
            if (startshapeName) {
                this.startshape = compiler_1.compileReplacement.call(this, ['REPLACEMENT', startshapeName, ['ADJUSTMENTS', []]]);
            }
        }
        /**
         * Compile rules into executable functions
         */
        compileRules() {
            // Create rules for primitives
            let n = 0;
            for (const name in this.primitives) {
                const render = this.primitives[name];
                this.rules[name] = [
                    {
                        replacements: [
                            function (transform, color, _targetColor, z, _zScale) {
                                const area = Math.abs(transform[0] * transform[3] - transform[1] * transform[2]);
                                if (area * this.scale * this.scale < 0.3)
                                    return;
                                const shape = {
                                    render,
                                    transform,
                                    color,
                                    area,
                                    z
                                };
                                this.shapes.push(shape);
                                if (!this.clip) {
                                    const size = Math.sqrt(area);
                                    shape.left = transform[4] - size;
                                    shape.right = transform[4] + size;
                                    shape.top = transform[5] - size;
                                    shape.bottom = transform[5] + size;
                                    if (this.left > shape.left)
                                        this.left = shape.left;
                                    if (this.right < shape.right)
                                        this.right = shape.right;
                                    if (this.top > shape.top)
                                        this.top = shape.top;
                                    if (this.bottom < shape.bottom)
                                        this.bottom = shape.bottom;
                                    if (this.width < this.right - this.left ||
                                        this.height < this.bottom - this.top) {
                                        this.width = this.right - this.left;
                                        this.height = this.bottom - this.top;
                                        this.scale = Math.min(this.canvas.width / this.width, this.canvas.height / this.height);
                                        if (n++ > 100 && this.shapes.length > 1000) {
                                            n = 0;
                                            this.shapes = this.shapes.filter((shape) => {
                                                return shape.area * this.scale * this.scale > 0.3;
                                            });
                                        }
                                    }
                                }
                            }
                        ],
                        probability: 1
                    }
                ];
            }
            // Compile user-defined rules
            for (const name in this.rules) {
                if (name in this.primitives)
                    continue;
                const sum = this.rules[name].reduce((sum, rule) => sum + (rule.weight || 0), 0);
                this.rules[name].forEach((rule) => {
                    rule.probability = (rule.weight || 0) / sum;
                    rule.replacements = compiler_1.compileReplacements.call(this, rule.replacements);
                });
            }
        }
        /**
         * Render the context-free design
         * @param callback - Called when rendering is complete
         */
        render(callback) {
            this.callback = callback || null;
            // Initialize canvas
            renderer_1.initializeCanvas.call(this, this.background);
            // Start expansion
            expansion_1.expandShape.call(this, () => renderer_1.drawShape.call(this));
        }
        /**
         * Stop the rendering process
         */
        stop() {
            renderer_1.stop.call(this);
        }
    }
    exports.ContextFree = ContextFree;
    if (typeof window !== 'undefined') {
        window.ContextFree = ContextFree;
    }
    
    return module.exports.ContextFree || module.exports;
  })();


  // Export the main ContextFree class to global scope
  var ContextFreeModule = modules['./contextfree'];
  if (typeof window !== 'undefined') {
    window.ContextFree = ContextFreeModule.ContextFree || ContextFreeModule;
  }
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = ContextFreeModule.ContextFree || ContextFreeModule;
  }
  
})();
