#!/usr/bin/env node

/**
 * Build script to generate cfdg.js with Chevrotain parser
 * This replaces the old Jison-based generate.js
 */

const fs = require('fs');
const path = require('path');

// Read the Chevrotain library (minified ES module)
const chevrotainPath = path.join(__dirname, 'node_modules', 'chevrotain', 'lib', 'chevrotain.min.mjs');
let chevrotainCode = fs.readFileSync(chevrotainPath, 'utf8');

// Convert ES module to browser-compatible format by extracting exports
// The minified file has exports at the end - we need to capture and convert them
// Match: export{...};
const exportMatch = chevrotainCode.match(/export\s*\{([^}]+)\}\s*;/);
if (!exportMatch) {
    throw new Error('Could not find export statement in Chevrotain code');
}

// Remove the export statement (it's at the end of the file)
chevrotainCode = chevrotainCode.replace(/export\s*\{[^}]+\}\s*;/, '');

// Read the parser template
const parserTemplate = fs.readFileSync(path.join(__dirname, 'cfdg-parser-template.js'), 'utf8');

// Parse the exports from the match
// Format is: "internalName as ExternalName" or just "name"
const exportMapping = exportMatch[1].split(',').map(e => {
    const parts = e.trim().split(' as ');
    if (parts.length > 1) {
        // Return "ExternalName: internalName"
        return `${parts[1].trim()}: ${parts[0].trim()}`;
    } else {
        // Return "name: name"
        const name = parts[0].trim();
        return `${name}: ${name}`;
    }
});

// Combine into single file
const output = `/* CFDG Parser - Generated with Chevrotain */
/* DO NOT EDIT THIS FILE DIRECTLY - Edit cfdg-parser-template.js and run generate.js */

// ============= Chevrotain Library =============
var chevrotain = (function() {
${chevrotainCode.split('\n').map(line => '  ' + line).join('\n')}
  
  // Return the exports (map internal names to external names)
  return {
    ${exportMapping.join(',\n    ')}
  };
})();

// ============= CFDG Parser =============
${parserTemplate}
`;

fs.writeFileSync(path.join(__dirname, 'cfdg.js'), output);
console.log('Successfully generated cfdg.js with Chevrotain parser!');
